name: AdPlay for DOS CI/CD

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [djgpp-2.0.5-gcc-12.2.0, djgpp-2.0.5-gcc-4.8.5]

      fail-fast: false

    runs-on: ${{matrix.os}}

    steps:
        - uses: actions/checkout@v3
    
        - name: Install packages (Linux)
          if: ${{ runner.os == 'Linux' }}
          run: |
            sudo apt update
            sudo apt install -y texlive-latex-base texinfo   
   
            if [[ ${{ matrix.compiler }} = djgpp* ]]; then
              # Flex is required, but even though it's in the GitHub runner image, and marked as installed
              # it's still missing some things, see https://github.com/orgs/community/discussions/45029
              sudo apt install -y libfl2 libfl-dev
    
              if [[ ${{ matrix.compiler }} == "djgpp-2.0.5-gcc-12.2.0" ]]; then
                wget https://github.com/andrewwutw/build-djgpp/releases/download/v3.4/djgpp-linux64-gcc1220.tar.bz2
                bzcat djgpp-linux64-gcc1220.tar.bz2 | sudo tar -x --directory /usr/local
              fi
              if [[ ${{ matrix.compiler }} == "djgpp-2.0.5-gcc-4.8.5" ]]; then
                wget https://github.com/andrewwutw/build-djgpp/releases/download/v1.6/djgpp-linux64-gcc485.tar.bz2
                bzcat djgpp-linux64-gcc485.tar.bz2 | sudo tar -x --directory /usr/local
              fi
            fi
    
        - name: Set DJGPP environment
          if: ${{ startsWith(matrix.compiler, 'djgpp') }}
          run: |
            echo 'compile_opts=--host=i586-pc-msdosdjgpp --prefix=/usr/local/djgpp CXXFLAGS=-Wno-deprecated CPPFLAGS=-Wno-deprecated PKG_CONFIG_PATH=/usr/local/djgpp/lib/pkgconfig' >> $GITHUB_ENV
            echo 'usr/local//djgpp/bin/' >> $GITHUB_PATH
    
        - name: Install libbinio
          run: |
            git clone http://github.com/adplug/libbinio.git
            pushd libbinio && autoreconf -i && ./configure --enable-maintainer-mode ${{ env.compile_opts }} && make && sudo env PATH=$PATH make install && popd
    
        - name: autoreconf
          run: autoreconf -i
        - name: configure
          run: ./configure ${{ env.compile_opts }} || cat config.log
    
        - name: make
          run: |
            ulimit -c unlimited -S
            if [[ ${{ matrix.compiler }} = djgpp* ]]; then
              # Just verify it compiles and installs,
              # we can't run tests because of binary incompatibility with host OS when cross compiling
    
              # Note: compile_opts is not used here, since DJGPP requires stuff like --host for ./configure
              # which will mess with make's command-line parsing
              make all

# TODO: build GCC
# TODO: Build adplay DOS

  # build-adplay:

  #       name: Build gcctimer
  #       run: | 
  #         docker exec mydjgppinstance bash -c "source /djgpp/setenv && /build/adplay-dos/build/build-gcctimer.sh"

  #     - 
  #       name: Build Adplay DOS
  #       run: | 
  #         docker exec mydjgppinstance bash -c "source /djgpp/setenv && /build/adplay-dos/build/build-adplay-dos.sh"
  #     -
  #       name: Upload artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: adplay
  #         path: |
  #           *.zip
