name: AdPlay for DOS CI/CD

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [djgpp-2.0.5-gcc-12.2.0, djgpp-2.0.5-gcc-4.8.5]

      fail-fast: false

    runs-on: ${{matrix.os}}

    steps:
        - name: Checkout AdPlug
          uses: actions/checkout@v4
          with:
            repository: 'adplug/adplug'
            ref: 'db2cb13954adf124eed768ef62c8ba7d926f0d39' # Target this commit, this contains patches for Adplug to provide DJGPP/Adplay DOS compatibility. Leave as is until new version is released
            path: adplug
        - name: Checkout libbinio
          uses: actions/checkout@v4
          with:
            repository: 'adplug/libbinio'
            path: libbinio
        - name: Checkout gcctimer
          uses: actions/checkout@v4
          with:
            repository: 'adplug/gcctimer'
            path: gcctimer
        - name: Checkout AdPlay for DOS (this repository)
          uses: actions/checkout@v4
          with:
            path: adplay
    
        - name: Install packages (Linux)
          if: ${{ runner.os == 'Linux' }}
          run: |
            sudo apt update
            sudo apt install -y texlive-latex-base texinfo libfl2 libfl-dev
            # Flex is required, but even though it's in the GitHub runner image, and marked as installed
            # it's still missing some things, see https://github.com/orgs/community/discussions/45029
   
            if [[ ${{ matrix.compiler }} == "djgpp-2.0.5-gcc-12.2.0" ]]; then
              wget https://github.com/andrewwutw/build-djgpp/releases/download/v3.4/djgpp-linux64-gcc1220.tar.bz2
              bzcat djgpp-linux64-gcc1220.tar.bz2 | sudo tar -x --directory /usr/local
            fi
            if [[ ${{ matrix.compiler }} == "djgpp-2.0.5-gcc-4.8.5" ]]; then
              wget https://github.com/andrewwutw/build-djgpp/releases/download/v1.6/djgpp-linux64-gcc485.tar.bz2
              bzcat djgpp-linux64-gcc485.tar.bz2 | sudo tar -x --directory /usr/local
            fi
   
        - name: Set DJGPP environment
          run: |
            echo 'compile_opts=--host=i586-pc-msdosdjgpp --prefix=/usr/local/djgpp CXXFLAGS=-Wno-deprecated CPPFLAGS=-Wno-deprecated PKG_CONFIG_PATH=/usr/local/djgpp/lib/pkgconfig' >> $GITHUB_ENV
            echo 'usr/local//djgpp/bin/' >> $GITHUB_PATH
    
        - name: Install libbinio
          run: |
            pushd libbinio && autoreconf -i && ./configure --enable-maintainer-mode ${{ env.compile_opts }} && make && sudo env PATH=$PATH make install && popd
    
        - name: autoreconf AdPlug
          run: pushd adplug && autoreconf -i && popd
        - name: configure AdPlug
          run: pushd adplug && ./configure ${{ env.compile_opts }} || cat config.log && popd
    
        - name: make AdPlug
          run: |
            ulimit -c unlimited -S
            pushd adplug
            # Note: compile_opts is not used here, since DJGPP requires stuff like --host for ./configure
            # which will mess with make's command-line parsing
            sudo env PATH=$PATH make install
            popd

        - name: Install gcctimer
          run: |
            pushd gcctimer
            make env PATH=$PATH CC=gcc prefix=/usr/local/djgpp # gcctimer does not have configure, so we cannot copy compile_opts
            sudo env PATH=$PATH CC=gcc prefix=/usr/local/djgpp make install
            popd

        - name: Build AdPlay for DOS
          run: |
            cd adplay
            cd window
            make
            sudo env PATH=$PATH make install
            cd ..
            make binarydist
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: adplay
            path: |
              adplay/*.zip
